server:
  port: 8002
spring:
  application:
    name: user
  security:
    user:
      name: 123qwe
      password: 123qwe
# Eureka的默认注册地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:${server.port}/eureka/