server:
  port: 8001
spring:
  application:
    name: feign
  security:
    user:
      name: 123qwe
      password: 123qwe
# Eureka的默认注册地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@localhost:9000/eureka/